// <auto-generated />
using System;
using MakeAWishDB.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MakeAWishDB.Migrations
{
    [DbContext(typeof(SharedData_Entities))]
    [Migration("20250830162800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MakeAWishDB.Entities.CakeAllergen", b =>
                {
                    b.Property<int>("CakeAllergenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CakeAllergenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CakeAllergenId"));

                    b.Property<int>("CelebrationCakeId")
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CakeAllergenId")
                        .HasName("PK__CakeAlle__76ADC3D9FC6080B0");

                    b.HasIndex("CelebrationCakeId");

                    b.HasIndex("IngredientId");

                    b.ToTable("CakeAllergens");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CakeFilling", b =>
                {
                    b.Property<int>("CakeFillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CakeFillingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CakeFillingId"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CakeFillingId")
                        .HasName("PK__CakeFill__71C3570A252C7797");

                    b.ToTable("CakeFillings");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CakeRecipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecipeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("CelebrationCakeId")
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeID");

                    b.Property<int>("CelebrationCakeSizeId")
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeSizeID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("RecipeId")
                        .HasName("PK__CakeReci__FDD988D01E35817D");

                    b.HasIndex("CelebrationCakeSizeId");

                    b.HasIndex("IngredientId");

                    b.HasIndex(new[] { "CelebrationCakeId", "CelebrationCakeSizeId" }, "index_recipes_cake_size");

                    b.ToTable("CakeRecipes", t =>
                        {
                            t.HasTrigger("trigger_CakeRecipes_Delete");

                            t.HasTrigger("trigger_CakeRecipes_Delete_DeactivateAllergens");

                            t.HasTrigger("trigger_CakeRecipes_Insert");

                            t.HasTrigger("trigger_CakeRecipes_Insert_Allergens");

                            t.HasTrigger("trigger_CakeRecipes_Update");

                            t.HasTrigger("trigger_CakeRecipes_Update_Allergens");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CelebrationCake", b =>
                {
                    b.Property<int>("CelebrationCakeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CelebrationCakeId"));

                    b.Property<int>("CakeFilling")
                        .HasColumnType("int");

                    b.Property<bool?>("ChildrenOffer")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("LowSugar")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("NoSugar")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PriceLarge")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PriceMedium")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("PriceSmall")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<bool?>("Vegan")
                        .HasColumnType("bit");

                    b.Property<bool?>("WeddingOffer")
                        .HasColumnType("bit");

                    b.Property<bool?>("WithAlcohol")
                        .HasColumnType("bit");

                    b.Property<bool?>("WithFruits")
                        .HasColumnType("bit");

                    b.Property<bool?>("WithNuts")
                        .HasColumnType("bit");

                    b.HasKey("CelebrationCakeId")
                        .HasName("PK__Celebrat__545A5A522EB28E60");

                    b.HasIndex("CakeFilling");

                    b.ToTable("CelebrationCakes", t =>
                        {
                            t.HasTrigger("trigger_DeleteProductBasedOnelebrationCakes");

                            t.HasTrigger("trigger_InsertCelebrationCakeToProducts");

                            t.HasTrigger("trigger_UpdateProductsBasedOnCelebrationCakes");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CelebrationCakeSize", b =>
                {
                    b.Property<int>("CelebrationCakeSizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CelebrationCakeSizeId"));

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CelebrationCakeSizeId")
                        .HasName("PK__Celebrat__72BBF00B609C94D9");

                    b.ToTable("CelebrationCakeSizes");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ContactMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MessageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int?>("Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsReplied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("MessageId")
                        .HasName("PK__ContactM__C87C037C2C85FD68");

                    b.HasIndex("Customer");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryAbbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Countrie__3214EC07512BC5E0");

                    b.HasIndex(new[] { "CountryAbbreviation" }, "UQ__Countrie__0F71A1ED6680DA07")
                        .IsUnique();

                    b.HasIndex(new[] { "CountryName" }, "UQ__Countrie__E056F201E44B3207")
                        .IsUnique();

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Country")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("DeliveryCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryPostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryStreet")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryStreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Fax")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool?>("IsCompany")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Nip")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("NIP");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Region")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Regon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("REGON");

                    b.Property<string>("SearchTerm")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StreetNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64B89F80E383");

                    b.HasIndex("Country");

                    b.HasIndex("Region");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<bool>("IsAllergenic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsVegan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    b.HasKey("IngredientId")
                        .HasName("PK__Ingredie__BEAEB27ABD481B7C");

                    b.HasIndex("UnitId");

                    b.HasIndex(new[] { "IsAvailable" }, "index_ingredients_isavailable");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.IngredientReservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CelebrationCakeSizeId")
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeSizeID");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    b.Property<decimal>("QuantityReserved")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ReservationId")
                        .HasName("PK__Ingredie__B7EE5F04A724586C");

                    b.HasIndex("CelebrationCakeSizeId");

                    b.HasIndex(new[] { "IngredientId" }, "index_reservations_ingredient");

                    b.HasIndex(new[] { "OrderItemId" }, "index_reservations_orderitem");

                    b.HasIndex(new[] { "IsCancelled" }, "index_reservations_status");

                    b.HasIndex(new[] { "IsUsed" }, "index_reservations_usage");

                    b.ToTable("IngredientReservations");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DueDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime")
                        .HasComputedColumnSql("(case when [PaymentMethod]=(3) then dateadd(day,(14),[CreatedAt])  end)", true);

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date");

                    b.Property<string>("InvoiceNumber")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(67)
                        .HasColumnType("nvarchar(67)")
                        .HasComputedColumnSql("((((('FV/'+CONVERT([nvarchar],datepart(year,[InvoiceDate])))+'/')+right('0'+CONVERT([nvarchar],datepart(month,[InvoiceDate])),(2)))+'/')+CONVERT([nvarchar],[InvoiceID]))", true);

                    b.Property<bool?>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalGross")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(20, 8)")
                        .HasComputedColumnSql("([TotalNet]+([TotalNet]*[VATRate])/(100))", true);

                    b.Property<decimal>("TotalNet")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("TotalVat")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 8)")
                        .HasColumnName("TotalVAT")
                        .HasComputedColumnSql("(([TotalNet]*[VATRate])/(100))", true);

                    b.Property<decimal?>("Vatrate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4, 2)")
                        .HasDefaultValue(23.00m)
                        .HasColumnName("VATRate");

                    b.HasKey("InvoiceId")
                        .HasName("PK__Invoices__D796AAD50FB24066");

                    b.HasIndex("PaymentMethod");

                    b.HasIndex(new[] { "OrderId" }, "index_invoices_order");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("InvoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InvoiceItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceItemId"));

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int")
                        .HasColumnName("InvoiceID");

                    b.Property<decimal?>("LineTotal")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(21, 2)")
                        .HasComputedColumnSql("([Quantity]*[UnitPrice])", true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("InvoiceItemId")
                        .HasName("PK__InvoiceI__478FE0FCD1F6EC69");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.LongArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("PageHeaderId")
                        .HasColumnType("int")
                        .HasColumnName("PageHeaderID");

                    b.Property<string>("Section1Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section1Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section2Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section2Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section3Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section3Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section4Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section4Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section5Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section5Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section6Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section6Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Section7Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section7Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ArticleId")
                        .HasName("PK__LongArti__9C6270C8D1CD4465");

                    b.HasIndex("PageHeaderId");

                    b.ToTable("LongArticles");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.MainPageArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ArticleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArticleId"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ArticleId")
                        .HasName("PK__MainPage__9C6270C8D011781F");

                    b.ToTable("MainPageArticles");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModuleId")
                        .HasName("PK__Modules__2B7477879B416450");

                    b.HasIndex(new[] { "ModuleName" }, "UQ__Modules__EAC9AEC3AFBB1771")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ModuleAccess", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("ModuleID");

                    b.Property<bool>("HasAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("RoleId", "ModuleId")
                        .HasName("PK__ModuleAc__E84D8942AE4D833D");

                    b.HasIndex("ModuleId");

                    b.ToTable("ModuleAccess");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool?>("IsPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Shop")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAF44AD5B3E");

                    b.HasIndex("Customer");

                    b.HasIndex("Shop");

                    b.HasIndex(new[] { "OrderDate" }, "index_orders_orderdate");

                    b.HasIndex(new[] { "Status" }, "index_orders_status");

                    b.ToTable("Orders", t =>
                        {
                            t.HasTrigger("trigger_AutoCancelIngredientReservations");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("CelebrationCake")
                        .HasColumnType("int");

                    b.Property<int?>("CelebrationCakeSize")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PersonalizedText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("OrderItemId")
                        .HasName("PK__OrderIte__57ED06A183952EF7");

                    b.HasIndex("CelebrationCakeSize");

                    b.HasIndex(new[] { "CelebrationCake" }, "index_orderitems_cake");

                    b.HasIndex(new[] { "OrderId" }, "index_orderitems_order");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.OrderStep", b =>
                {
                    b.Property<int>("OrderStepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderStepID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStepId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.HasKey("OrderStepId")
                        .HasName("PK__OrderSte__64CE5BB1327EC3B7");

                    b.HasIndex(new[] { "StepNo" }, "UQ__OrderSte__2434686271605109")
                        .IsUnique();

                    b.ToTable("OrderSteps");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.PageHeader", b =>
                {
                    b.Property<int>("PageHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PageHeaderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PageHeaderId"));

                    b.Property<string>("DisplayedHeader")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("InternalName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PageHeaderId")
                        .HasName("PK__PageHead__B6F5E8091F76D526");

                    b.HasIndex(new[] { "InternalName" }, "UQ__PageHead__CAD7CE323DE0811F")
                        .IsUnique()
                        .HasFilter("[InternalName] IS NOT NULL");

                    b.ToTable("PageHeaders");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("PaymentMethodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PaymentMethodID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentMethodId"));

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentMethodId")
                        .HasName("PK__PaymentM__DC31C1F34F89F601");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CelebrationCakeId")
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeID");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6ED76A06646");

                    b.HasIndex("ProductCategory");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ProductCategoryId")
                        .HasName("PK__ProductC__3224ECEE66C212BC");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.QuoteRequest", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QuoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuoteId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Customer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DesiredDeliveryDate")
                        .HasColumnType("date");

                    b.Property<string>("GuestEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsConvertedToOrder")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("UploadedImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("QuoteId")
                        .HasName("PK__QuoteReq__AF9688E17EDA8951");

                    b.HasIndex("Customer");

                    b.HasIndex(new[] { "CreatedAt" }, "index_quotes_created");

                    b.HasIndex(new[] { "Status" }, "index_quotes_status");

                    b.ToTable("QuoteRequests");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Recomendation", b =>
                {
                    b.Property<int>("RecomendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecomendationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecomendationId"));

                    b.Property<int>("CelebrationCake")
                        .HasColumnType("int");

                    b.HasKey("RecomendationId")
                        .HasName("PK__Recomend__0EF51DC0B009ED34");

                    b.HasIndex(new[] { "CelebrationCake" }, "UQ__Recomend__46385E408BDB0A0C")
                        .IsUnique();

                    b.ToTable("Recomendations");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RegionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryID");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegionId")
                        .HasName("PK__Regions__ACD84443E2426DD2");

                    b.HasIndex("CountryId");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Shop", b =>
                {
                    b.Property<int>("ShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShopID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShopId"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GoogleMapsURL");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OpeningHoursMdFr")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OpeningHoursSt")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StreetAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ShopId")
                        .HasName("PK__Shops__67C55629D721EE63");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ShoppingCartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CelebrationCakeId")
                        .HasColumnType("int")
                        .HasColumnName("CelebrationCakeID");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("SessionToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("CartItemId")
                        .HasName("PK__Shopping__488B0B2AB87E3588");

                    b.HasIndex("CelebrationCakeId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StatusId")
                        .HasName("PK__Statuses__C8EE206375D7C1E5");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Stock", b =>
                {
                    b.Property<int>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StockID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StockId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("QuantityAvailable")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("StockId")
                        .HasName("PK__Stock__2C83A9E28969CB2B");

                    b.HasIndex(new[] { "IngredientId" }, "index_stock_ingredient");

                    b.ToTable("Stock", null, t =>
                        {
                            t.HasTrigger("tr_AutoRestockHandler_Multi");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.StockShortage", b =>
                {
                    b.Property<int>("ShortageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShortageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShortageId"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    b.Property<decimal>("QuantityMissing")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ShortageId")
                        .HasName("PK__StockSho__6423218244215EAD");

                    b.HasIndex(new[] { "IngredientId", "IsValid" }, "index_shortages_ingredient_valid");

                    b.HasIndex(new[] { "OrderItemId" }, "index_shortages_orderitem");

                    b.ToTable("StockShortages");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TeamMemberID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageURL");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeamMemberId")
                        .HasName("PK__TeamMemb__C7C09285EC34D6D1");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UnitID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UnitId"));

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UnitId")
                        .HasName("PK__Units__44F5EC956539BDD0");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__UserAcco__1788CCAC56D1F1EE");

                    b.HasIndex("UserRole");

                    b.HasIndex(new[] { "Username" }, "UQ__UserAcco__536C85E48A608285")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.UserRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__UserRole__8AFACE3AD1017CAB");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ViewCurrentStockShortage", b =>
                {
                    b.Property<string>("CakeName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("Customer")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("IngredientID");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int")
                        .HasColumnName("OrderItemID");

                    b.Property<decimal>("QuantityMissing")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("RecordedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("ShortageId")
                        .HasColumnType("int")
                        .HasColumnName("ShortageID");

                    b.ToTable((string)null);

                    b.ToView("view_CurrentStockShortages", (string)null);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ViewNewOrder", b =>
                {
                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("Shop")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.ToTable((string)null);

                    b.ToView("view_NewOrders", (string)null);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ViewNewQuoteRequest", b =>
                {
                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DesiredDeliveryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsConvertedToOrder")
                        .HasColumnType("bit");

                    b.Property<int>("QuoteId")
                        .HasColumnType("int")
                        .HasColumnName("QuoteID");

                    b.Property<string>("RequesterEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequesterName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StatusName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UploadedImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.ToTable((string)null);

                    b.ToView("view_NewQuoteRequests", (string)null);
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CakeAllergen", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CelebrationCake", "CelebrationCake")
                        .WithMany("CakeAllergens")
                        .HasForeignKey("CelebrationCakeId")
                        .IsRequired()
                        .HasConstraintName("FK__CakeAller__Celeb__02C769E9");

                    b.HasOne("MakeAWishDB.Entities.Ingredient", "Ingredient")
                        .WithMany("CakeAllergens")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__CakeAller__Ingre__03BB8E22");

                    b.Navigation("CelebrationCake");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CakeRecipe", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CelebrationCake", "CelebrationCake")
                        .WithMany("CakeRecipes")
                        .HasForeignKey("CelebrationCakeId")
                        .IsRequired()
                        .HasConstraintName("FK__CakeRecip__Celeb__2BFE89A6");

                    b.HasOne("MakeAWishDB.Entities.CelebrationCakeSize", "CelebrationCakeSize")
                        .WithMany("CakeRecipes")
                        .HasForeignKey("CelebrationCakeSizeId")
                        .IsRequired()
                        .HasConstraintName("FK__CakeRecip__Celeb__2CF2ADDF");

                    b.HasOne("MakeAWishDB.Entities.Ingredient", "Ingredient")
                        .WithMany("CakeRecipes")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__CakeRecip__Ingre__2DE6D218");

                    b.Navigation("CelebrationCake");

                    b.Navigation("CelebrationCakeSize");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CelebrationCake", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CakeFilling", "CakeFillingNavigation")
                        .WithMany("CelebrationCakes")
                        .HasForeignKey("CakeFilling")
                        .IsRequired()
                        .HasConstraintName("FK__Celebrati__CakeF__60A75C0F");

                    b.Navigation("CakeFillingNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ContactMessage", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Customer", "CustomerNavigation")
                        .WithMany("ContactMessages")
                        .HasForeignKey("Customer")
                        .HasConstraintName("FK__ContactMe__IsRep__09A971A2");

                    b.Navigation("CustomerNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Customer", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Country", "CountryNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("Country")
                        .IsRequired()
                        .HasConstraintName("FK__Customers__Count__5441852A");

                    b.HasOne("MakeAWishDB.Entities.Region", "RegionNavigation")
                        .WithMany("Customers")
                        .HasForeignKey("Region")
                        .HasConstraintName("FK__Customers__Regio__5535A963");

                    b.Navigation("CountryNavigation");

                    b.Navigation("RegionNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Ingredient", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Unit", "Unit")
                        .WithMany("Ingredients")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__UnitI__25518C17");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.IngredientReservation", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CelebrationCakeSize", "CelebrationCakeSize")
                        .WithMany("IngredientReservations")
                        .HasForeignKey("CelebrationCakeSizeId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__Celeb__339FAB6E");

                    b.HasOne("MakeAWishDB.Entities.Ingredient", "Ingredient")
                        .WithMany("IngredientReservations")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__Ingre__3493CFA7");

                    b.HasOne("MakeAWishDB.Entities.OrderItem", "OrderItem")
                        .WithMany("IngredientReservations")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK__Ingredien__IsCan__32AB8735");

                    b.Navigation("CelebrationCakeSize");

                    b.Navigation("Ingredient");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Invoice", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__Invoices__OrderI__17F790F9");

                    b.HasOne("MakeAWishDB.Entities.PaymentMethod", "PaymentMethodNavigation")
                        .WithMany("Invoices")
                        .HasForeignKey("PaymentMethod")
                        .IsRequired()
                        .HasConstraintName("FK__Invoices__Paymen__18EBB532");

                    b.Navigation("Order");

                    b.Navigation("PaymentMethodNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.InvoiceItem", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Invoice", "Invoice")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("InvoiceId")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceIt__Invoi__1CBC4616");

                    b.HasOne("MakeAWishDB.Entities.Product", "Product")
                        .WithMany("InvoiceItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK__InvoiceIt__Produ__1DB06A4F");

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.LongArticle", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.PageHeader", "PageHeader")
                        .WithMany("LongArticles")
                        .HasForeignKey("PageHeaderId")
                        .IsRequired()
                        .HasConstraintName("FK__LongArtic__PageH__10566F31");

                    b.Navigation("PageHeader");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ModuleAccess", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Module", "Module")
                        .WithMany("ModuleAccesses")
                        .HasForeignKey("ModuleId")
                        .IsRequired()
                        .HasConstraintName("FK__ModuleAcc__Modul__43D61337");

                    b.HasOne("MakeAWishDB.Entities.UserRole", "Role")
                        .WithMany("ModuleAccesses")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__ModuleAcc__RoleI__42E1EEFE");

                    b.Navigation("Module");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Order", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Customer", "CustomerNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Customer")
                        .HasConstraintName("FK__Orders__Customer__74AE54BC");

                    b.HasOne("MakeAWishDB.Entities.Shop", "ShopNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Shop")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__Shop__75A278F5");

                    b.HasOne("MakeAWishDB.Entities.Status", "StatusNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__Status__76969D2E");

                    b.Navigation("CustomerNavigation");

                    b.Navigation("ShopNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.OrderItem", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CelebrationCake", "CelebrationCakeNavigation")
                        .WithMany("OrderItems")
                        .HasForeignKey("CelebrationCake")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Celeb__7C4F7684");

                    b.HasOne("MakeAWishDB.Entities.CelebrationCakeSize", "CelebrationCakeSizeNavigation")
                        .WithMany("OrderItems")
                        .HasForeignKey("CelebrationCakeSize")
                        .HasConstraintName("FK__OrderItem__Celeb__7B5B524B");

                    b.HasOne("MakeAWishDB.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK__OrderItem__Order__7A672E12");

                    b.Navigation("CelebrationCakeNavigation");

                    b.Navigation("CelebrationCakeSizeNavigation");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Product", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.ProductCategory", "ProductCategoryNavigation")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategory")
                        .IsRequired()
                        .HasConstraintName("FK__Products__Produc__5BE2A6F2");

                    b.Navigation("ProductCategoryNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.QuoteRequest", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Customer", "CustomerNavigation")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("Customer")
                        .HasConstraintName("FK__QuoteRequ__Custo__03F0984C");

                    b.HasOne("MakeAWishDB.Entities.Status", "StatusNavigation")
                        .WithMany("QuoteRequests")
                        .HasForeignKey("Status")
                        .IsRequired()
                        .HasConstraintName("FK__QuoteRequ__Statu__02FC7413");

                    b.Navigation("CustomerNavigation");

                    b.Navigation("StatusNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Recomendation", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CelebrationCake", "CelebrationCakeNavigation")
                        .WithOne("Recomendation")
                        .HasForeignKey("MakeAWishDB.Entities.Recomendation", "CelebrationCake")
                        .IsRequired()
                        .HasConstraintName("FK__Recomenda__Celeb__6477ECF3");

                    b.Navigation("CelebrationCakeNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Region", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Country", "Country")
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Regions__Country__4D94879B");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ShoppingCartItem", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.CelebrationCake", "CelebrationCake")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("CelebrationCakeId")
                        .IsRequired()
                        .HasConstraintName("FK__ShoppingC__Celeb__4F47C5E3");

                    b.HasOne("MakeAWishDB.Entities.UserAccount", "User")
                        .WithMany("ShoppingCartItems")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__ShoppingC__UserI__4E53A1AA");

                    b.Navigation("CelebrationCake");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Stock", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Ingredient", "Ingredient")
                        .WithMany("Stocks")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__Stock__Ingredien__29221CFB");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.StockShortage", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.Ingredient", "Ingredient")
                        .WithMany("StockShortages")
                        .HasForeignKey("IngredientId")
                        .IsRequired()
                        .HasConstraintName("FK__StockShor__Ingre__395884C4");

                    b.HasOne("MakeAWishDB.Entities.OrderItem", "OrderItem")
                        .WithMany("StockShortages")
                        .HasForeignKey("OrderItemId")
                        .IsRequired()
                        .HasConstraintName("FK__StockShor__Order__3A4CA8FD");

                    b.Navigation("Ingredient");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.UserAccount", b =>
                {
                    b.HasOne("MakeAWishDB.Entities.UserRole", "UserRoleNavigation")
                        .WithMany("UserAccounts")
                        .HasForeignKey("UserRole")
                        .IsRequired()
                        .HasConstraintName("FK__UserAccou__UserR__498EEC8D");

                    b.Navigation("UserRoleNavigation");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CakeFilling", b =>
                {
                    b.Navigation("CelebrationCakes");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CelebrationCake", b =>
                {
                    b.Navigation("CakeAllergens");

                    b.Navigation("CakeRecipes");

                    b.Navigation("OrderItems");

                    b.Navigation("Recomendation");

                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.CelebrationCakeSize", b =>
                {
                    b.Navigation("CakeRecipes");

                    b.Navigation("IngredientReservations");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Country", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Customer", b =>
                {
                    b.Navigation("ContactMessages");

                    b.Navigation("Orders");

                    b.Navigation("QuoteRequests");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Ingredient", b =>
                {
                    b.Navigation("CakeAllergens");

                    b.Navigation("CakeRecipes");

                    b.Navigation("IngredientReservations");

                    b.Navigation("StockShortages");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Module", b =>
                {
                    b.Navigation("ModuleAccesses");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.OrderItem", b =>
                {
                    b.Navigation("IngredientReservations");

                    b.Navigation("StockShortages");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.PageHeader", b =>
                {
                    b.Navigation("LongArticles");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Product", b =>
                {
                    b.Navigation("InvoiceItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.ProductCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Region", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Shop", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Status", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("QuoteRequests");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.Unit", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.UserAccount", b =>
                {
                    b.Navigation("ShoppingCartItems");
                });

            modelBuilder.Entity("MakeAWishDB.Entities.UserRole", b =>
                {
                    b.Navigation("ModuleAccesses");

                    b.Navigation("UserAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
